CREATE TABLE auths (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    team VARCHAR(255),
    email VARCHAR(255) NOT NULL UNIQUE,
    hash VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(300),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (team) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE teams (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);